development:
    FACEBOOK_KEY: "210713559096811"
    FACEBOOK_SECRET: "a63fa71a4495d8987c7cb8cbc9b06b63"
    GCM_KEY: "AIzaSyC2yRXgOcumlbxWVakyVHZxX-8ks0OdLsc"        
    S3_BUCKET_NAME: "com.copicious.staging"
    AWS_ACCESS_KEY_ID: "AKIAJ6OIPH5Y535SJZEQ"
    AWS_SECRET_ACCESS_KEY: "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"
    ENDEC_KEY: "e52e30262a5b0806d1ebfed41ae685d1"
    FOG_DIRECTORY: "copicious-assets"
production:
    FACEBOOK_KEY: "570630822972350"
    FACEBOOK_SECRET: "6b079a4b015f811d28d54ba0059ef1db"    
    GCM_KEY: "AIzaSyDQVvriMeMfXTTuQSnzao0KomOsbqA3F4Q"
    S3_BUCKET_NAME: "com.copicious.www"
    AWS_ACCESS_KEY_ID: "AKIAJ6OIPH5Y535SJZEQ"
    AWS_SECRET_ACCESS_KEY: "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"
    ENDEC_KEY: "e52e30262a5b0806d1ebfed41ae685d1"
    FOG_DIRECTORY: "copicious-assets"
staging:
    FACEBOOK_KEY: "473081492790728"
    FACEBOOK_SECRET: "75c118af70e66868ad4d7f911171ed8f"    
    GCM_KEY: "AIzaSyDQVvriMeMfXTTuQSnzao0KomOsbqA3F4Q"
    S3_BUCKET_NAME: "com.copicious.staging"
    AWS_ACCESS_KEY_ID: "AKIAJ6OIPH5Y535SJZEQ"
    AWS_SECRET_ACCESS_KEY: "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"
    ENDEC_KEY: "e52e30262a5b0806d1ebfed41ae685d1"
    FOG_DIRECTORY: "copicious-assets"
