# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34cadfe392a290f2621f4cbac4b0e734f30ac0b119eefe4254aa6196dc110da88b90715c45b5acbdc3df9c792cdf517b02632965890b47fe5ad0c96ab132945b

test:
  secret_key_base: d6f32d0580f342a572300af86cb527902f132bc15e14522e2ea74ba9adddf5ef252b251e891de4f87b6e4634deef1d6f544312c2a8eb568cf2f0ffbfb9b27091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
