# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

unless Rpush::Gcm::App.any?
  app = Rpush::Gcm::App.new
  app.name = "android_app"
  app.auth_key = "AIzaSyDvovMZRqsuEeN8KwuZ0qwLIwh1A16MxSs"
  app.connections = 1
  app.save!
end

# unless Rpush::Apns::App.any?
#   app = Rpush::Apns::App.new
#   app.name = "ios"
#   app.certificate = File.read Rails.root.join('docs','sandbox.pem')
#   app.environment = "sandbox" # APNs environment.
#   app.password = ENV['APNS_PASSWORD']
#   app.connections = 1
#   app.save!
# end

UserPercentage.create(ptype: 'Jobseeker', key: 'resume', value: 40)
UserPercentage.create(parent_id: 1, ptype: 'Jobseeker', key: 'resume_info', value: 50)
UserPercentage.create(parent_id: 1, ptype: 'Jobseeker', key: 'education', value: 25)
UserPercentage.create(parent_id: 1, ptype: 'Jobseeker', key: 'experience', value: 13)
UserPercentage.create(parent_id: 1, ptype: 'Jobseeker', key: 'prework', value: 12)
UserPercentage.create(ptype: 'Jobseeker', key: 'achievement', value: 10)
UserPercentage.create(parent_id: 6, ptype: 'Jobseeker', key: 'award', value: 50)
UserPercentage.create(parent_id: 6, ptype: 'Jobseeker', key: 'certificate', value: 50)
UserPercentage.create(ptype: 'Jobseeker', key: 'extra', value: 10)
UserPercentage.create(ptype: 'Jobseeker', key: 'whizquiz', value: 10)
UserPercentage.create(ptype: 'Jobseeker', key: 'futuregoal', value: 10)
UserPercentage.create(ptype: 'Jobseeker', key: 'workingenv', value: 10)
UserPercentage.create(ptype: 'Jobseeker', key: 'references', value: 10)



UserPercentage.create(ptype: 'Company', key: 'info', value: 50)
UserPercentage.create(ptype: 'Company', key: 'corporate', value: 10)
UserPercentage.create(ptype: 'Company', key: 'growth', value: 10)
UserPercentage.create(parent_id: 16, ptype: 'Company', key: 'evalution', value: 50)
UserPercentage.create(parent_id: 16, ptype: 'Company', key: 'futuregoal', value: 50)
UserPercentage.create(ptype: 'Company', key: 'achievement', value: 10)
UserPercentage.create(parent_id: 19, ptype: 'Company', key: 'award', value: 50)
UserPercentage.create(parent_id: 19, ptype: 'Company', key: 'certificate', value: 50)
UserPercentage.create(ptype: 'Company', key: 'gallery', value: 10)
UserPercentage.create(ptype: 'Company', key: 'workingenv', value: 10)



UserPercentage.create(ptype: 'Student', key: 'info', value: 20)
UserPercentage.create(ptype: 'Student', key: 'education', value: 40)
UserPercentage.create(parent_id: 25, ptype: 'Student', key: 'education', value: 50)
UserPercentage.create(parent_id: 25, ptype: 'Student', key: 'marksheet', value: 40)
UserPercentage.create(parent_id: 25, ptype: 'Student', key: 'project', value: 10)
UserPercentage.create(ptype: 'Student', key: 'achievement', value: 20)
UserPercentage.create(parent_id: 29, ptype: 'Student', key: 'award', value: 50)
UserPercentage.create(parent_id: 29, ptype: 'Student', key: 'certificate', value: 50)
UserPercentage.create(ptype: 'Student', key: 'extra', value: 10)
UserPercentage.create(ptype: 'Student', key: 'futuregoal', value: 10)



UserPercentage.create(ptype: 'Faculty', key: 'info', value: 20)
UserPercentage.create(ptype: 'Faculty', key: 'experience', value: 60)
UserPercentage.create(parent_id: 35, ptype: 'Faculty', key: 'affiliation', value: 30)
UserPercentage.create(parent_id: 35, ptype: 'Faculty', key: 'workshop', value: 30)
UserPercentage.create(parent_id: 35, ptype: 'Faculty', key: 'publication', value: 20)
UserPercentage.create(parent_id: 35, ptype: 'Faculty', key: 'research', value: 20)
UserPercentage.create(ptype: 'Faculty', key: 'achievement', value: 20)
UserPercentage.create(parent_id: 40, ptype: 'Faculty', key: 'award', value: 50)
UserPercentage.create(parent_id: 40, ptype: 'Faculty', key: 'certificate', value: 50)

UserPercentage.create(ptype: 'site', key: 'like', value: 8)
UserPercentage.create(parent_id: 43, ptype: 'site', key: 'like_first', value: 100)
UserPercentage.create(parent_id: 43, ptype: 'site', key: 'like_second', value: 300)
UserPercentage.create(parent_id: 43, ptype: 'site', key: 'like_third', value: 500)
UserPercentage.create(ptype: 'site', key: 'star', value: 8)
UserPercentage.create(parent_id: 43, ptype: 'site', key: 'star_first', value: 100)
UserPercentage.create(parent_id: 43, ptype: 'site', key: 'star_second', value: 300)
UserPercentage.create(parent_id: 43, ptype: 'site', key: 'star_third', value: 500)
UserPercentage.create(ptype: 'site', key: 'updateinfo', value: 8)
UserPercentage.create(parent_id: 48, ptype: 'site', key: 'update_first', value: 10)
UserPercentage.create(parent_id: 48, ptype: 'site', key: 'update_second', value: 30)
UserPercentage.create(parent_id: 48, ptype: 'site', key: 'update_third', value: 50)
UserPercentage.create(ptype: 'site', key: 'share', value: 8)
UserPercentage.create(parent_id: 52, ptype: 'site', key: 'share_first', value: 100)
UserPercentage.create(parent_id: 52, ptype: 'site', key: 'share_second', value: 300)
UserPercentage.create(parent_id: 52, ptype: 'site', key: 'share_third', value: 500)
UserPercentage.create(ptype: 'site', key: 'viewed', value: 8)
UserPercentage.create(parent_id: 56, ptype: 'site', key: 'view_first', value: 100)
UserPercentage.create(parent_id: 56, ptype: 'site', key: 'view_second', value: 300)
UserPercentage.create(parent_id: 56, ptype: 'site', key: 'view_third', value: 500)
UserPercentage.create(ptype: 'site', key: 'marketIQ', value: 15)
UserPercentage.create(parent_id: 60, ptype: 'site', key: 'market_first', value: 100)
UserPercentage.create(parent_id: 60, ptype: 'site', key: 'market_second', value: 300)
UserPercentage.create(parent_id: 60, ptype: 'site', key: 'market_third', value: 500)
UserPercentage.create(ptype: 'site', key: 'stockexchange', value: 35)
UserPercentage.create(parent_id: 64, ptype: 'site', key: 'stock_first', value: 100)
UserPercentage.create(parent_id: 64, ptype: 'site', key: 'stock_second', value: 300)
UserPercentage.create(parent_id: 64, ptype: 'site', key: 'stock_third', value: 500)
UserPercentage.create(ptype: 'site', key: 'profilemeter', value: 10)




user = User.create(email: 'admin@example.com', password: '12345678' , username: 'admin' , role: 'Admin', user_total_per:10 )
user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)

# user = User.create!(email: 'trupti@gmail.com', password:'12345678' , username: 'trupti' , role: 'Student', first_name: 'trupti' , user_total_per:30) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'anni@gmail.com', password:'12345678' , username: 'anni' , role: 'Student', first_name: 'anni' , user_total_per:40) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'julia@gmail.com', password:'12345678' , username: 'julia' , role: 'Student', first_name: 'julia' , user_total_per:50) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'mary@gmail.com', password:'12345678' , username: 'mary' , role: 'Student', first_name: 'mary' , user_total_per:60) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'nicolecross1579@gmail.com', password:'12345678' , username: 'nicole' , role: 'Student', first_name: 'nicole' , user_total_per:70) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'kianstokes@gmail.com', password:'12345678' , username: 'kianstokes' , role: 'Student', first_name: 'kianstokes' , user_total_per:80) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)

# user = User.create!(email: 'daisy@gmail.com', password: '12345678' , username: 'daisy' , role: 'Faculty', user_total_per:90 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'jekky@gmail.com', password: '12345678' , username: 'jekky' , role: 'Faculty', user_total_per:10 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'angela@gmail.com', password: '12345678' , username: 'angela' , role: 'Faculty', user_total_per:20 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'diana@gmail.com', password: '12345678' , username: 'diana' , role: 'Faculty', user_total_per:30 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)

# user = User.create!(email: 'gunja@gmail.com', password:'12345678' , username: 'gunja' , role: 'Jobseeker', first_name: 'sam', middle_name: 'deo', last_name: 'jacson', city: 'pune', address: 'street 4,near community hall', nationality: "Indian", contact_number: 9988776655 , user_total_per:40) 
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'sam@gmail.com', password: '12345678' , username: 'sam' , role: 'Jobseeker', first_name: 'sam', middle_name: 'deo', last_name: 'jacson', city: 'pune', address: 'street 4,near community hall', nationality: "Indian", contact_number: 9988776655, user_total_per:50 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'riya@gmail.com', password: '12345678' , username: 'riya' , role: 'Jobseeker', first_name: 'sam', middle_name: 'deo', last_name: 'jacson', city: 'pune', address: 'street 4,near community hall', nationality: "Indian", contact_number: 9988776655, user_total_per:60 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'self@gmail.com', password: '12345678' , username: 'self' , role: 'Jobseeker', first_name: 'sam', middle_name: 'deo', last_name: 'jacson', city: 'pune', address: 'street 4,near community hall', nationality: "Indian", contact_number: 9988776655, user_total_per:70 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'thomas@gmail.com', password: '12345678' , username: 'thomas' , role: 'Jobseeker', first_name: 'sam', middle_name: 'deo', last_name: 'jacson', city: 'pune', address: 'street 4,near community hall', nationality: "Indian", contact_number: 9988776655, user_total_per:80 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'victor@gmail.com', password: '12345678' , username: 'victor' , role: 'Jobseeker', first_name: 'sam', middle_name: 'deo', last_name: 'jacson', city: 'pune', address: 'street 4,near community hall', nationality: "Indian", contact_number: 9988776655, user_total_per:90 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)


# user = User.create!(email: 'parnel@gmail.com', password: '12345678' , username: 'parnel' , role: 'Company', user_total_per:10 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'kriya@gmail.com', password: '12345678' , username: 'kriya' , role: 'Company', user_total_per:20 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'niya@gmail.com', password: '12345678' , username: 'niya' , role: 'Company', user_total_per:30 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)
# user = User.create!(email: 'abc@gmail.com', password: '12345678' , username: 'abc' , role: 'Company', user_total_per:40 )
# user.devices << Device.create!(uuid: SecureRandom.uuid , 	registration_id: SecureRandom.uuid)


Course.create(name: "be")
Course.create(name: "me")
Course.create(name: "mba")
Course.create(name: "phd")
Course.create(name: "btech")
Course.create(name: "mca")
Course.create(name: "bca")
Course.create(name: "commerce")
Course.create(name: "science")
Course.create(name: "arts")
Course.create(name: "cooking")

Company.create(name: "E Commerce")
Company.create(name: "Social Media")
Company.create(name: "Marketplace")
Company.create(name: "Product Development")
Company.create(name: "Public")
Company.create(name: "Software Development")
Company.create(name: "Corporation")
Company.create(name: "Web Development")
Company.create(name: "Healthcare Technology")
Company.create(name: "Business Consulting")
Company.create(name: "Marketing Services")

Industry.create(name: "Agriculture & Forestry")
Industry.create(name: "Business & Information")
Industry.create(name: "Education")
Industry.create(name: "Finance & Insurance")
Industry.create(name: "Food & Hospitality")
Industry.create(name: "Gaming")
Industry.create(name: "Health Services")
Industry.create(name: "Motor Vehicle")
Industry.create(name: "Natural Resources")
Industry.create(name: "Personal Services")
Industry.create(name: "Real Estate & Housing")

Specialization.create(name: "computer")
Specialization.create(name: "electrical")
Specialization.create(name: "information technology")
Specialization.create(name: "civil")
Specialization.create(name: "power and electronics")
Specialization.create(name: "chemical")
Specialization.create(name: "mechanical")
Specialization.create(name: "software engineering")
Specialization.create(name: "systems engineering")
Specialization.create(name: "textiles")
Specialization.create(name: "mining")

# UserAward.create(user_id: 3, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 4, name:'sss', award_type:'sas', description:'aaa')
# UserAward.create(user_id: 5, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 6, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 7, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 8, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 9, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 10, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 11, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 12, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 13, name:'aaa', award_type:'xcv', description:'fgh')
# UserAward.create(user_id: 14, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 15, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 16, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 17, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 18, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 19, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 20, name:'zxc', award_type:'hju', description:'vbf')
# UserAward.create(user_id: 21, name:'abc', award_type:'pqr', description:'xyz')
# UserAward.create(user_id: 22, name:'sss', award_type:'sas', description:'aaa')

# UserCertificate.create(user_id: 3,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 4,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 5,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 6,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 7,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 8,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 9,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 10,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 11,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 12,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 13,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 14,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 15,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 16,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 17,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 18,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 19,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 20,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 21,name:'mno', certificate_type:'jkl', year:2011)
# UserCertificate.create(user_id: 22,name:'mno', certificate_type:'jkl', year:2011)


# UserCurricular.create(user_id: 3, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 4, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 5, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 6, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 7, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 8, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 9, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 10, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 11, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 12, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 13, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 14, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 15, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 16, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 17, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 18, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 19, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 20, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')
# UserCurricular.create(user_id: 21, curricular_type:'xyz', team_type:'abc', location:'jamnagar', date:'22/11/2011')
# UserCurricular.create(user_id: 22, curricular_type:'vcd', team_type:'cds', location:'junagadh', date:'22/11/2011')

# UserEducation.create(user_id: 3, course_id:3, specialization_id:3,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 4, course_id:4, specialization_id:4,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 5, course_id:5, specialization_id:5,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 6, course_id:6, specialization_id:6,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 7, course_id:7, specialization_id:7,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 8, course_id:8, specialization_id:8,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 9, course_id:9, specialization_id:9,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 10, course_id:10, specialization_id:10,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 11, course_id:11, specialization_id:11,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 12, course_id:1, specialization_id:1,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 13, course_id:2, specialization_id:2,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 14, course_id:3, specialization_id:3,  year:2011, school: 'vivekanand', skill: 'dancing')
# UserEducation.create(user_id: 15, course_id:4, specialization_id:4,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 16, course_id:5, specialization_id:5,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 17, course_id:6, specialization_id:6,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 18, course_id:7, specialization_id:7,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 19, course_id:8, specialization_id:8,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 20, course_id:9, specialization_id:9,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 21, course_id:10, specialization_id:10,  year:2011, school: 'modi', skill: 'singing')
# UserEducation.create(user_id: 22, course_id:11, specialization_id:11,  year:2011, school: 'modi', skill: 'singing')


# StudentEducation.create(user_id: 3, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 3, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 3, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 4, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 4, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 4, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 5, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 5, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 5, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 6, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 6, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 6, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 7, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 7, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 7, standard: 'abcdefg',  year:2011, school: 'vivekanand' )
# StudentEducation.create(user_id: 8, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 8, standard: 'abcdefg',  year:2011, school: 'modi' )
# StudentEducation.create(user_id: 8, standard: 'abcdefg',  year:2011, school: 'vivekanand' )



# UserEnvironment.create(user_id: 3, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 4, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 5, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 6, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 7, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 8, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 9, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 10, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 11, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 12, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 13, env_type: 'qwert', title: 'title')
# UserEnvironment.create(user_id: 14, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 15, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 16, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 17, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 18, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 19, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 20, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 21, env_type: 'cvfds', title: 'dfgtr')
# UserEnvironment.create(user_id: 22, env_type: 'cvfds', title: 'dfgtr')


# UserExperience.create(user_id: 3, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 4, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 5, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 6, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 7, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 8, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 9, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 10, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 11, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 12, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 13, name: 'zxcvb', start_from: '22/10/2012', working_till: '22/11/2011', designation:'tester')
# UserExperience.create(user_id: 14, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 15, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 16, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 17, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 18, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 19, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 20, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 21, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')
# UserExperience.create(user_id: 22, name: 'sade', start_from: '22/10/2012', working_till: '22/11/2011', designation:'dev')


# UserFutureGoal.create(user_id: 3, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# UserFutureGoal.create(user_id: 4, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# UserFutureGoal.create(user_id: 5, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# UserFutureGoal.create(user_id: 6, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# UserFutureGoal.create(user_id: 7, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# UserFutureGoal.create(user_id: 8, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# # UserFutureGoal.create(user_id: 9, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# # UserFutureGoal.create(user_id: 10, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# # UserFutureGoal.create(user_id: 11, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# # UserFutureGoal.create(user_id: 12, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 13, goal_type: 'zasdew', title: 'hjure', term_type: 'ghjk')
# UserFutureGoal.create(user_id: 14, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 15, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 16, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 17, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 18, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 19, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 20, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 21, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')
# UserFutureGoal.create(user_id: 22, goal_type: 'asdf', title: 'fgtr', term_type: 'ghyt')


# UserPreferredWork.create(user_id: 3, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 4, ind_name: 'Infosys', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 5, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 6, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 7, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 8, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 9, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 10, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 11, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 12, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 13, ind_name: 'Krishaweb', functional_name: 'backend',  preferred_designation: 'developer', preferred_location: 'ahmedabad', current_salary: '10000', expected_salary: '20000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 14, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 15, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 16, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 17, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 18, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 19, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 20, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 21, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')
# UserPreferredWork.create(user_id: 22, ind_name: 'Transenergy', functional_name: 'frontend',  preferred_designation: 'hr', preferred_location: 'rajkot', current_salary: '20000', expected_salary: '30000', time_type: 'fulltime')


# UserReference.create(user_id: 3, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 4, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 5, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 6, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 7, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 8, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 9, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 10, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 11, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 12, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 13, title: 'my ref', ref_type: 'individual', from: 'mr.joseph', email: 'jk@gmail.com', contact: '9988776655', date: '22/11/2011', location: 'asxde')
# UserReference.create(user_id: 14, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 15, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 16, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 17, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 18, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 19, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 20, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 21, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')
# UserReference.create(user_id: 22, title: 'own ref', ref_type: 'company', from: 'miss.anna', email: 'one@gmail.com', contact: '1234567890', date: '30/11/2011', location: 'zawer')

# UserMarksheet.create(user_id: 7,school_name: 'sdfgh', standard: 'first', grade: 'A', year: 2011)
# UserMarksheet.create(user_id: 8,school_name: 'qwertyu', standard: 'third', grade: 'C', year: 2011)
# UserMarksheet.create(user_id: 9,school_name: 'sdfgh', standard: 'first', grade: 'A', year: 2011)
# UserMarksheet.create(user_id: 10,school_name: 'qwertyu', standard: 'third', grade: 'C', year: 2011)
# UserMarksheet.create(user_id: 7,school_name: 'sdfgh', standard: 'first', grade: 'A', year: 2011)
# UserMarksheet.create(user_id: 8,school_name: 'qwertyu', standard: 'third', grade: 'C', year: 2011)
# UserMarksheet.create(user_id: 9,school_name: 'sdfgh', standard: 'first', grade: 'A', year: 2011)

# UserProject.create(user_id: 7,title: 'sdfgh', description: 'first')
# UserProject.create(user_id: 8,title: 'qwertyu', description: 'third')
# UserProject.create(user_id: 9,title: 'sdfgh', description: 'first')
# UserProject.create(user_id: 10,title: 'qwertyu', description: 'third')
# UserProject.create(user_id: 7,title: 'sdfgh', description: 'first')
# UserProject.create(user_id: 8,title: 'qwertyu', description: 'third')
# UserProject.create(user_id: 9,title: 'sdfgh', description: 'first')

# FacultyAffiliation.create(user_id:7, university:'gtu', collage_name: 'vgec', subject: 'computer', designation: 'chandkheda', join_from: '22/11/2011' )
# FacultyAffiliation.create(user_id:8, university:'gtu', collage_name: 'vgec', subject: 'computer', designation: 'chandkheda', join_from: '22/11/2011' )
# FacultyAffiliation.create(user_id:9, university:'gtu', collage_name: 'vgec', subject: 'computer', designation: 'chandkheda', join_from: '22/11/2011' )
# FacultyAffiliation.create(user_id:10, university:'gtu', collage_name: 'vgec', subject: 'computer', designation: 'chandkheda', join_from: '22/11/2011' )


# FacultyPublication.create(user_id:7, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )
# FacultyPublication.create(user_id:8, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )
# FacultyPublication.create(user_id:9, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )
# FacultyPublication.create(user_id:10, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )

# FacultyResearch.create(user_id:7, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )
# FacultyResearch.create(user_id:8, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )
# FacultyResearch.create(user_id:9, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )
# FacultyResearch.create(user_id:10, title:'abcdefghijklmnopqrstuvwxyz', description: 'abcdefghijklmnopqrstuvwxyz' )

# FacultyWorkshop.create(user_id:7, description:'abcdefghijklmnopqrstuvwxyz' )
# FacultyWorkshop.create(user_id:8, description:'abcdefghijklmnopqrstuvwxyz' )
# FacultyWorkshop.create(user_id:9, description:'abcdefghijklmnopqrstuvwxyz' )
# FacultyWorkshop.create(user_id:10, description:'abcdefghijklmnopqrstuvwxyz' )

# Group.create(name: 'daisygroup', slug: 'daisygroup', code: 123456 )
# Group.create(name: 'jekkygroup', slug: 'jekkygroup', code: 123456 )
# Group.create(name: 'angelagroup', slug: 'angelagroup', code: 123456 )
# Group.create(name: 'dianagroup', slug: 'dianagroup', code: 123456 )


Setting.create(resume_per: 40, achievement_per: 10, curricular_per: 10, whizquiz_per: 10, future_goal_per: 10, working_env_per: 10,reference_per: 10,site_name: 'Selfie Cv', site_email: 'selfiecv@gmailcom',site_phone: 12345678,site_fax: 1234567,facebook_url:'http://www.facebook.com/selfiecv',twitter_url:'http://www.twitter.com/selfiecv',google_plus_url: 'http://www.googleplus.com/selfiecv')

QuickMessage.create(text: 'Your homework for today is.', role: 'faculty')
QuickMessage.create(text: 'Great work class !! Keep it up !!', role: 'faculty')
QuickMessage.create(text: 'Tommorrow we will be starting a new chapter. Make sure you dont miss it.', role: 'faculty')
QuickMessage.create(text: 'Many students are having problems with current chapter. I know its difficult but dont worry i am always here to help you.', role: 'faculty')
QuickMessage.create(text: 'You have a surprise test tomorrow.', role: 'faculty')
QuickMessage.create(text: 'Life teaching : The best preparation for tomorrow is doing your best today.', role: 'faculty')
QuickMessage.create(text: 'If you are facing any perticular problem, do feel free to share with me.', role: 'faculty')

QuickMessage.create(text: 'My query for current chapter.', role: 'student')
QuickMessage.create(text: 'Thank you for help mam/sir.', role: 'student')
QuickMessage.create(text: 'I will not able to come class tomorrow due to fever.', role: 'student')



Whizquiz.create(question: 'Grand Central Terminal, Park Avenue, New York is the worlds', answer: 'largest railway station', status: true)
Whizquiz.create(question: 'Entomology is the science that studies', answer: 'Insects', status: true)
Whizquiz.create(question: 'Eritrea, which became the 182nd member of the UN in 1993, is in the continent of', answer: 'Africa')
Whizquiz.create(question: 'Brass gets discoloured in air because of the presence of which of the following gases in air?', answer: 'Hydrogen sulphide')
Whizquiz.create(question: 'Which of the following is a non metal that remains liquid at room temperature?', answer: 'Bromine', status: true)
Whizquiz.create(question: 'Chlorophyll is a naturally occurring chelate compound in which central metal is', answer: 'magnesium', status: true)
Whizquiz.create(question: 'The name of the Laccadive, Minicoy and Amindivi islands was changed to Lakshadweep by an Act of Parliament in', answer: '1973', status: true)
Whizquiz.create(question: 'The members of the Rajya Sabha are elected by', answer: 'elected members of the legislative assembly', status: true)
Whizquiz.create(question: 'The power to decide an election petition is vested in the', answer: 'High courts')
Whizquiz.create(question: 'The present Lok Sabha is the', answer: '16th Lok Sabha')
Whizquiz.create(question: 'The Homolographic projection has the correct representation of', answer: 'area', status: true)
Whizquiz.create(question: 'The intersecting lines drawn on maps and globes are', answer: 'geographic grids')
Whizquiz.create(question: 'The nucleus of an atom consists of', answer: 'protons and neutrons')
Whizquiz.create(question: 'The most electronegative element among the following is', answer: 'fluorine')
Whizquiz.create(question: 'The metal used to recover copper from a solution of copper sulphate is', answer: 'Fe')
Whizquiz.create(question: 'The metallurgical process in which a metal is obtained in a fused state is called', answer: 'smelting')







